### ISSUE TITLE
سوال در مورد رپو

### ISSUE THREAD

**Issue by majidh1** [mohammadzarax/publicSwa#1]
سلام من این رپوزیتوری رو دیدم یه فایل دارید به اسم tensorflow میخوام بدونم قراره کاری کنید تو این رپو فقط یه رپو دیگه داشتید که پاک شده توی اون خیلی کامل‌تر بود این بخش بیشتر به دلیل اون رپو ایشو زدم

**Comment by mohammadzarax** [comment]
سلام روی رپو NLP خیلی کار کرده بودم و نمیخواستم دیگه پابلیک باشه دلیله اینکه مشاهده نمیکنید اینه
حالا لطفا به من پیام بدین @mohammadzarax  تلگرام
